services:

  tagger:
    build:
      context: ./backend/v1
      dockerfile: Dockerfile
    command: [ "-m", "aitcore.v1.tagger", "--loglevel", "INFO" ]
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./.env
    image: ait/backend:latest
    networks:
      - aitnw
    volumes:
      - aitagger:/aitagger

networks:
  aitnw:


volumes:
  aitagger:
    driver: local
