services:
  frontend:
    build:
      context: ./frontend/v1
      dockerfile: Dockerfile
    depends_on:
      - backendsvcs
    env_file:
      - ./.env
    image: ait/frontend:latest
    ports:
      - 3000:80
    networks:
      - aitnw
    restart: unless-stopped

  backendsvcs:
    build:
      context: ./backend/v1
      dockerfile: Dockerfile
    command: [ "-m", "aitapi.v1.router", "--port", "8880", "--loglevel", "INFO" ]
    env_file:
      - ./.env
    image: ait/backendsvcs:latest
    networks:
      - aitnw
    ports:
      - 8880:8880

networks:
  aitnw:


volumes:
  aitagger:
    driver: local
